const data = {
  users: [
    {
      name: "admin",

      email: "admin@admin.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "admin2",
      email: "admin2@admin.com",
      password: "1234567",
      role: "admin",
    },
    {
      name: "admin3",
      email: "admin3@admin.com",
      password: "1234567",
      role: "client",
    },
    {
      name: "HARI",
      email: "srmdpk12325@gmail.com",
      password: "654321",
      role: "client",
    },
  ],
  products: [
    {
      name: "King Size Lobet",
      slug: "lo-1",
      category: "Lobet",
      image: `/images/products/lo-1.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Lobet",
    },
    {
      name: "King Size Lobet",
      slug: "lo-2",
      category: "Lobet",
      image: `/images/products/lo-2.jpg`,
      price: 290000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Lobet",
    },
    {
      name: "King Size Lobet",
      slug: "lo-3",
      category: "Lobet",
      image: `/images/products/lo-3.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Lobet",
    },
    {
      name: "King Size Lobet",
      slug: "lo-4",
      category: "Lobet",
      image: `/images/products/lo-4.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Lobet",
    },
    {
      name: "King Size Box-Palang",
      slug: "bp-1",
      category: "Box-Palang",
      image: `/images/products/bp-1.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Box-Palang",
    },
    {
      name: "King Size Box-Palang",
      slug: "bp-2",
      category: "Box-Palang",
      image: `/images/products/bp-2.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Box-Palang",
    },
    {
      name: "King Size Box-Palang",
      slug: "bp-3",
      category: "Box-Palang",
      image: `/images/products/bp-3.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Box-Palang",
    },
    {
      name: "King Size Box-Palang",
      slug: "bp-4",
      category: "Box-Palang",
      image: `/images/products/bp-4.jpg`,
      price: 2900,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Box-Palang",
    },
    {
      name: "King Size Box-Palang",
      slug: "bp-5",
      category: "Box-Palang",
      image: `/images/products/bp-5.jpg`,
      price: 2900,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Box-Palang",
    },
    {
      name: "King Size Daraz",
      slug: "da-1",
      category: "Daraz",
      image: `/images/products/da-1.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Daraz",
    },
    {
      name: "King Size Daraz",
      slug: "da-2",
      category: "Daraz",
      image: `/images/products/da-2.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Daraz",
    },
    {
      name: "King Size Sofa",
      slug: "so-1",
      category: "Sofa",
      image: `/images/products/so-1.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Sofa",
    },
    {
      name: "King Size Sofa",
      slug: "so-2",
      category: "Sofa",
      image: `/images/products/so-2.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Sofa",
    },
    {
      name: "King Size Daraz",
      slug: "da-3",
      category: "Daraz",
      image: `/images/products/da-3.jpg`,
      price: 29000,
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular 6*4 size Daraz",
    },
  ],
};
export default data;
