const data = {
  users: [
    {
      name: "admin",
      email: "admin@admin.com",
      password: "123456",
      isAdmin: true,
    },
    {
      name: "admin2",
      email: "admin2@admin.com",
      password: "1234567",
      isAdmin: false,
    },
    {
      name: "admin3",
      email: "admin3@admin.com",
      password: "1234567",
      isAdmin: false,
    },
    {
      name: "HARI",
      email: "srmdpk12325@gmail.com",
      password: "654321",
      isAdmin: false,
    },
  ],
  products: [
    {
      id: 1,
      name: "Free-Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular Shirt",
    },
    {
      id: 2,
      name: "Fit-Pant",
      slug: "fit-pant",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "Brand New PAnt",
    },
    {
      id: 3,
      name: "Swet Shirt",
      slug: "swet-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 60,
      brand: "Gucci",
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular Shirt",
    },
    {
      id: 4,
      name: "Long-Vest",
      slug: "long-Vest",
      category: "Vest",
      image: "/images/pants2.jpg",
      price: 50,
      brand: "Armani",
      rating: 4.5,
      numReview: 8,
      countInStock: 20,
      description: "A Popular Vest",
    },
  ],
};
export default data;
